<?php
/**
 * Image gallery
 *
 * @param AbstractObject $object
 * @param string|null    $image_id
 *
 * @return string
 */
function flat_image_gallery($object, $image_id = null) {

    module_load_include('inc', 'flat_image_gallery', 'includes/FlatImageGallery');
    module_load_include('inc', 'flat_image_gallery', 'includes/FlatImageGallerySolr');

    drupal_add_css(drupal_get_path('module', 'flat_image_gallery') . '/css/flat-image-gallery-app.css');

    $solr     = new FlatImageGallerySolr();
    $gallery  = new FlatImageGallery($object, $solr, $image_id);

    $images   = $gallery->getImages();
    $current  = $gallery->getCurrentImage();

    if (false === $current) {

        return theme('flat_image_gallery_out_of_bounds', [
            'url' => url('islandora/object/' . $object->id . '/ig'),
        ]);
    }

    return theme('flat_image_gallery_overview', [

        'islandora_object' => $object,
        'images'           => $images,
        'current'          => $current,
        'navigationLinks'  => $gallery->getNavigationLinks(),
        'paginationLinks'  => $gallery->getPaginationLinks(),
    ]);
}

function flat_image_gallery_ajax($page_callback_result) {

    // Add CSS and JS files, add some markup
    $html = '<html><head><title></title>' . drupal_get_css() . drupal_get_js() . '</head><body>' . $page_callback_result . '</body></html>';
    print $html;

    // Perform end-of-request tasks.
    drupal_page_footer();
}

/**
 * Preprocessor to add link to gallery at the top of the block
 *
 * @param array $variables
 *
 * @return void
 */
function flat_image_gallery_preprocess_block(&$variables) {

    if (isset($variables['block_html_id']) && $variables['block_html_id'] === 'block-system-main') {

        module_load_include('inc', 'flat_image_gallery', 'includes/FlatImageGallerySolr');

        $pid     = arg(2);
        $solr    = new FlatImageGallerySolr();
        $results = $solr->getImages($pid);

        if ($results['total'] > 0) {

            drupal_add_js(drupal_get_path('module', 'flat_image_gallery') . '/js/flat-image-gallery-app.js');
            drupal_add_css(drupal_get_path('module', 'flat_image_gallery') . '/css/flat-image-gallery-app.css');

            $content              = theme('flat_image_gallery_modal', ['url' => url('islandora/object/' . $pid . '/ig')]);
            $variables['content'] = $content . $variables['content'];
        }
    }
}

/**
 * Image Gallery Menu
 *
 * @return array
 */
function flat_image_gallery_menu() {

    $items = [];

    $items['islandora/object/%islandora_object/ig'] = [

        'title'             => 'Image Gallery',
        'type'              => MENU_CALLBACK,
        'page callback'     => 'flat_image_gallery',
        'page arguments'    => [2],
        'access callback'   => 'flat_image_gallery_menu_access',
        'delivery callback' => 'flat_image_gallery_ajax',
    ];

    return $items;
}

/**
 * Always allow image gallery menu access
 *
 * @return boolean
 */
function flat_image_gallery_menu_access() {
    return true;
}

/**
 * hook_theme implementation
 *
 * @param array  $existing
 * @param string $type
 * @param string $theme
 * @param string $path
 *
 * @return array
 */
function flat_image_gallery_theme($existing, $type, $theme, $path) {

    return [

        'flat_image_gallery_overview' => [
            'template' => 'theme/flat-image-gallery-overview',
        ],

        'flat_image_gallery_modal' => [
            'template' => 'theme/flat-image-gallery-modal',
        ],

        'flat_image_gallery_out_of_bounds' => [
            'template' => 'theme/flat-image-gallery-out-of-bounds',
        ],
    ];
}
