<?php
/**
 * Image gallery
 *
 * @param AbstractObject $object
 * @param string|null    $image_id
 *
 * @return string
 */
function flat_image_gallery($object, $image_id = null) {

    module_load_include('inc', 'flat_image_gallery', 'includes/FlatImageGallery');
    module_load_include('inc', 'islandora', 'includes/authtokens');
    module_load_include('inc', 'islandora', 'includes/solution_packs');

    drupal_add_css(drupal_get_path('module', 'flat_image_gallery') . '/css/flat-image-gallery-app.css');

    $gallery  = new FlatImageGallery($object, $image_id);
    $images   = $gallery->getImages();
    $current  = $gallery->getCurrentImage();
    $links    = $gallery->getNavigationLinks();

    return theme('flat_image_gallery_overview', [

        'images'          => $images,
        'current'         => $current,
        'navigationLinks' => $links,
    ]);
}

function flat_image_gallery_ajax($page_callback_result) {

    $content = drupal_render($page_callback_result);
    $html    = '<html><head><title></title>' . drupal_get_css() . drupal_get_js() . '</head></body class="jquery-ajax-load">' . $content . '</body></html>';

    print $html;

    drupal_page_footer();
}

function flat_image_gallery_islandora_compoundCModel_islandora_view_object($object) {

    drupal_add_js(drupal_get_path('module', 'flat_image_gallery') . '/js/flat-image-gallery-app.js');
    drupal_add_css(drupal_get_path('module', 'flat_image_gallery') . '/css/flat-image-gallery-app.css');

    return theme('flat_image_gallery_modal', ['url' => url('islandora/object/' . $object->id . '/ig')]);
}

/**
 * Image Gallery Menu
 *
 * @return array
 */
function flat_image_gallery_menu() {

    $items = [];

    $items['islandora/object/%islandora_object/ig'] = [

        'title'             => 'Image Gallery',
        'type'              => MENU_CALLBACK,
        'page callback'     => 'flat_image_gallery',
        'page arguments'    => [2],
        'access callback'   => 'flat_image_gallery_menu_access',
        'delivery callback' => 'flat_image_gallery_ajax',
    ];

    return $items;
}

/**
 * Always allow image gallery menu access
 *
 * @return boolean
 */
function flat_image_gallery_menu_access() {
    return true;
}

/**
 * hook_theme implementation
 *
 * @param array  $existing
 * @param string $type
 * @param string $theme
 * @param string $path
 *
 * @return array
 */
function flat_image_gallery_theme($existing, $type, $theme, $path) {

    return [

        'flat_image_gallery_overview' => [
            'template' => 'theme/flat-image-gallery-overview',
        ],

        'flat_image_gallery_modal' => [
            'template' => 'theme/flat-image-gallery-modal',
        ],
    ];
}
