<?php
define('FLAT_GALLERY_DEFAULT_PAGINATION_LIMIT', 10);
module_load_include('inc', 'islandora', 'includes/authtokens');
module_load_include('inc', 'islandora', 'includes/solution_packs');
/**
 * FLAT gallery
 *
 * @param AbstractObject $object
 * @param string|null    $id
 *
 * @return string
 */
function flat_gallery($object, $id = null) {

    module_load_include('inc', 'flat_gallery', 'includes/FlatGallery');
    module_load_include('inc', 'flat_gallery', 'includes/FlatGallerySolr');

    drupal_add_css(drupal_get_path('module', 'flat_gallery') . '/css/flat-gallery-app.css');

    $solr    = new FlatGallerySolr();
    $gallery = new FlatGallery($object, $solr, $id);

    $items   = $gallery->getItems();
    $current = $gallery->getCurrentItem();

    if (false === $current) {

        return theme('flat_gallery_out_of_bounds', [
            'url' => url('islandora/object/' . $object->id . '/ig'),
        ]);
    }

    return theme('flat_gallery_overview', [

        'islandora_object' => $object,
        'items'            => $items,
        'current'          => $current,
        'navigationLinks'  => $gallery->getNavigationLinks(),
        'paginationLinks'  => $gallery->getPaginationLinks(),
    ]);
}

/**
 * Ajax callback method
 *
 * @param string $page_callback_result
 *
 * @return void
 */
function flat_gallery_ajax($page_callback_result) {

    // Add CSS and JS files, add some markup
    $html = '<html><head><title></title>' . drupal_get_css() . drupal_get_js() . '</head><body>' . $page_callback_result . '</body></html>';
    print $html;

    // Perform end-of-request tasks.
    drupal_page_footer();
}

/**
 * Preprocessor to add link to gallery at the top of the block
 *
 * @param array $variables
 *
 * @return void
 */
function flat_gallery_preprocess_block(&$variables) {

    if (isset($variables['block_html_id']) && $variables['block_html_id'] === 'block-islandora-compound-object-compound-navigation') {

        module_load_include('inc', 'flat_gallery', 'includes/FlatGallerySolr');

        $pid     = urldecode(arg(2));
        $solr    = new FlatGallerySolr();
        $results = $solr->getItems($pid);

        if ($results['total'] > 0) {

            drupal_add_js(drupal_get_path('module', 'flat_gallery') . '/js/flat-gallery-app.js');
            drupal_add_css(drupal_get_path('module', 'flat_gallery') . '/css/flat-gallery-app.css');

            $content              = theme('flat_gallery_modal', ['url' => url('islandora/object/' . $pid . '/ig')]);
            $variables['content'] = $content . $variables['content'];
        }
    }
}

/**
 * FLAT Gallery Menu
 *
 * @return array
 */
function flat_gallery_menu() {

    $items = [];

    $items['islandora/object/%islandora_object/ig'] = [

        'title'             => 'FLAT Gallery',
        'type'              => MENU_CALLBACK,
        'page callback'     => 'flat_gallery',
        'page arguments'    => [2],
        'access callback'   => 'flat_gallery_menu_access',
        'delivery callback' => 'flat_gallery_ajax',
    ];

    $items['admin/config/flat_deposit/flat_gallery'] = [

        'title'           => 'Configure FLAT gallery',
        'type'            => MENU_LOCAL_TASK,
        'page callback'   => 'drupal_get_form',
        'page arguments'  => ['flat_gallery_admin_form'],
        'access callback' => 'flat_gallery_menu_access',
        'file'            => 'includes/FlatGalleryAdmin.inc',
    ];

    return $items;
}

/**
 * Always allow FLAT gallery menu access
 *
 * @return boolean
 */
function flat_gallery_menu_access() {
    return true;
}

/**
 * hook_theme implementation
 *
 * @param array  $existing
 * @param string $type
 * @param string $theme
 * @param string $path
 *
 * @return array
 */
function flat_gallery_theme($existing, $type, $theme, $path) {

    return [

        'flat_gallery_overview' => [
            'template' => 'theme/flat-gallery-overview',
        ],

        'flat_gallery_modal' => [
            'template' => 'theme/flat-gallery-modal',
        ],

        'flat_gallery_out_of_bounds' => [
            'template' => 'theme/flat-gallery-out-of-bounds',
        ],
    ];
}
